---
- hosts: localhost
  tasks:
    - name: Generate an SSH Key pair for using in Terraform templates
      openssh_keypair:
        path: ~/.ssh/id_rsa
        state: present
        type: rsa
        size: 2048
        force: no
